services:
    minimax-free-api:
        image: akashrajpuroh1t/minimax-free-api-fix:1.0.0
        container_name: ${CONTAINER_NAME}
        ports:
            - ${PANEL_APP_PORT_HTTP}:8000
        networks:
            - 1panel-network
        environment:
            - TZ=Asia/Shanghai
        labels:
            createdBy: Apps
        restart: always
networks:
    1panel-network:
        external: true
