services:
  searxng:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    volumes:
      - "${DATA_PATH}:/etc/searxng"
    environment:
      - BASE_URL=${SEARXNG_EXTERNAL_URL}
    image: searxng/searxng:2025.12.3-1f6ea4127
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
