services:
  glance-agent:
    container_name: ${CONTAINER_NAME}
    image: glanceapp/agent:v0.1.0
    environment:
      TOKEN: ${AGENT_TOKEN}
    volumes:
      - /storage:/storage:ro
    ports:
      - ${AGENT_PORT}:27973
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
