services:
  gpt-load:
    image: ghcr.io/tbphp/gpt-load:v1.4.0
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    networks:
      - 1panel-network
    volumes:
      - ./data:/app/data
    environment:
      - AUTH_KEY=${AUTH_KEY}
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
