services:
  trend-radar:
    image: wantcat/trendradar:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    volumes:
      - ../config:/app/config:ro
      - ${DATA_PATH}:/app/output
    environment:
      - TZ=Asia/Shanghai
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - RUN_MODE=${RUN_MODE}
      - IMMEDIATE_RUN=${IMMEDIATE_RUN}
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
  trend-radar-mcp:
    image: wantcat/trendradar-mcp:latest
    container_name: ${CONTAINER_NAME}-trend-radar-mcp
    restart: always
    ports:
      - ${MCP_PORT}:3333
    volumes:
      - ../config:/app/config:ro
      - ${DATA_PATH}:/app/output
    environment:
      - TZ=Asia/Shanghai
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
