services:
  inspector:
    image: ghcr.io/modelcontextprotocol/inspector:0.17.5
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6274
      - ${PANEL_APP_PORT_PROXY}:6277
    environment:
      - NODE_ENV=production
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - DANGEROUSLY_OMIT_AUTH=${DANGEROUSLY_OMIT_AUTH}
      - MCP_PROXY_AUTH_TOKEN=${MCP_PROXY_AUTH_TOKEN}
      - HOST=0.0.0.0
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
