services:
  dashboard:
    image: ghcr.io/nezhahq/nezha:v1.14.12
    container_name: ${CONTAINER_NAME}
    restart: always
    volumes:
      - ./data:/dashboard/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:8008
