services:
  n8n:
    image: n8nio/n8n:1.122.3
    container_name: ${CONTAINER_NAME}
    restart: always
    user: 1000:1000
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5678
    volumes:
      - ./data:/home/node/.n8n
      - ./editor-ui:/usr/local/lib/node_modules/n8n/node_modules/n8n-editor-ui/dist
    environment:
      N8N_SECURE_COOKIE: false
      N8N_DEFAULT_LOCALE: zh-CN
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
