services:
  trae-proxy:
    image: vuldocker/trae-proxy:1.0.0
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - ./ca:/app/ca
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true